openapi: 3.0.0
info:
  title: Swagger Pestore
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
tags:
  - name: form
    description: Everything about your user
  - name: hint
    description: Everything about your hint
  - name: record
    description: Everything about your record
  - name: programm
    description: Everything about your programm
  - name: user
    description: Everything about your user
paths:
  /form:
    get:
      tags:
        - form
      summary: フォームデータを返す
      parameters:
        - name: formName
          in: query
          description: "フォームの名前（英数字）を渡す"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 指定されたフォーム名のフォームデータを返す。
          content:
            application/json:
              schema:
                type: object
                properties:
                  formData:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        partType:
                          type: string
                        explanation:
                          type: string
                        childrenPart:
                          type: string

        "400":
          description: パラメータformNameは必須です
        "404":
          description: 指定されたフォーム名の回答テンプレートが見つかりません。
        "500":
          description: 何らかのエラーが発生しました
  /form/list:
    get:
      tags:
        - form
      summary: フォーム名の一覧を返す
      responses:
        "200":
          description: フォーム名の一覧を返す。
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    description:
                      type: string
                    url:
                      type: string
                    explanation:
                      type: string
                    inputExample:
                      type: array
                      items:
                        type: string
                    outputExample:
                      type: array
                      items:
                        type: string
        "404":
          description: フォームリストが空です。
        "500":
          description: 何らかのエラーが発生しました。
  /form/question:
    get:
      tags:
        - form
      summary: フォームの問題データを返す
      parameters:
        - name: formId
          in: query
          description: "フォームのIDを渡す"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 指定されたフォーム名の問題データを返す。
          content:
            application/json:
              schema:
                type: object
                properties:
                  questionData:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      explanation:
                        type: string
                      inputExample:
                        type: array
                        items:
                          type: string
                      outputExample:
                        type: array
                        items:
                          type: string
        "400":
          description: パラメータformIdは必須です
        "404":
          description: 指定されたformIdの問題データが見つかりません。
        "500":
          description: 何らかのエラーが発生しました。
  /hint:
    get:
      tags:
        - hint
      summary: フォームのヒントデータを返す
      responses:
        "200":
          description: フォームのヒントデータを返す。
          content:
            application/json:
              schema:
                type: object
                properties:
                  hintData:
                    type: array
                    items:
                      type: object
                      properties:
                        partType:
                          type: string
                        partTitle:
                          type: string
                        hintList:
                          type: object
                          properties:
                            hintType:
                              type: string
                            hintTitle:
                              type: string
                            hint:
                              type: string
        "404":
          description: ヒントデータが見つかりません。
        "500":
          description: 何らかのエラーが発生しました。
  /record:
    post:
      tags:
        - record
      summary: フォームの回答データを保存する
      requestBody:
        description: フォームの回答データを保存する
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                formName:
                  type: string
                fbData:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: number
                      partType:
                        type: string
                      currentHintStep:
                        type: number
                      ClickedHintStep:
                        type: number
                inputData:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: number
                      partType:
                        type: string
                      inputDataArray:
                        type: array
                        items:
                          type: string
      responses:
        "200":
          description: アップロードに成功しました。
        "400":
          description: 必要なデータが渡されていません。
        "404":
          description: 指定されたフォーム名の回答テンプレートが見つかりません。
        "500":
          description: 何らかのエラーが発生しました。
  /programm/exec-result:
    post:
      tags:
        - programm
      summary: プログラムを実行し、その結果を返す
      requestBody:
        description: プログラムを実行する
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                input:
                  type: string
      responses:
        "x-200-Ok":
          description: リクエストに成功し、コンパイルエラーがない場合、statusには"success"が返る。
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  output:
                    type: string
        "x-200-Ng":
          description: リクエストに成功し、コンパイルエラーがある場合、statusには"error"が返り、errorsにエラーメッセージの配列が返る。
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  errors:
                    type: array
                    items:
                      type: string
        "400":
          description: 必要なデータが渡されていません。
        "500":
          description: 何らかのエラーが発生しました。
  /programm/error/resolve:
    post:
      tags:
        - programm
      summary: プログラムエラーの解決法を返す
      requestBody:
        description: プログラムのエラーを解決する
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                errors:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: プログラムのエラーの解決法を返す。
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultMethods:
                    type: array
                    items:
                      type: object
                      properties:
                        error:
                          type: string
                        row:
                          type: number
                        column:
                          type: number
                        description:
                          type: string
                        method:
                          type: string
        "400":
          description: 必要なデータが渡されていません。
        "500":
          description: 何らかのエラーが発生しました。
  /programm/connected-code:
    post:
      tags:
        - programm
      summary: 入力したコードを１つのコードに結合して返す
      requestBody:
        description: 入力したコードを１つのコードに結合して返す
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                formData:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: number
                      partType:
                        type: string
                      explanation:
                        type: string
                      childrenPart:
                        type: string
                inputData:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: number
                      partType:
                        type: string
                      inputDataArray:
                        type: array
                        items:
                          type: string
      responses:
        "200":
          description: 結合されたコードを返す。
          content:
            application/json:
              schema:
                type: object
                properties:
                  connectedCode:
                    type: string
        "500":
          description: 何らかのエラーが発生しました。
  /user/login:
    post:
      tags:
        - user
      summary: ユーザーをログインさせる
      requestBody:
        description: ユーザーをログインさせる
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                password:
                  type: string
                mail:
                  type: string
      responses:
        "200":
          description: ログインに成功しました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  name:
                    type: string
                  icon:
                    type: string
                  mail:
                    type: string
        "400":
          description: 必要なデータが渡されていません。
        "404":
          description: ユーザーが見つかりません。
        "500":
          description: 何らかのエラーが発生しました。
  /user/register:
    post:
      tags:
        - user
      summary: ユーザーを登録する
      requestBody:
        description: ユーザーを登録する。passwordはハッシュ化して保存する。
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                password:
                  type: string
                name:
                  type: string
                icon:
                  type: string
                mail:
                  type: string
      responses:
        "200":
          description: 登録に成功しました。
        "400":
          description: 必要なデータが渡されていません。
        "409":
          description: 既に登録されているユーザーIDです。
        "500":
          description: 何らかのエラーが発生しました。
components:
  schemas:
    Form:
      type: object
      properties:
        id:
          type: number
        partType:
          type: string
        explanation:
          type: string
        childrenPart:
          type: string
    Hint:
      type: object
      properties:
        partType:
          type: string
        partTitle:
          type: string
        hintList:
          type: object
          properties:
            hintType:
              type: string
            hintTitle:
              type: string
            hint:
              type: string
    User:
      type: object
      properties:
        userId:
          type: string
        password:
          type: string
        name:
          type: string
        icon:
          type: string
        mail:
          type: string
