name: Pull Request Check
on: [pull_request]
jobs:
  pull_request_check:
    name: Pull Request Check
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
#      - name: install
#        run: npm install
#      - name: build check
#        run: npm run build
